apiVersion: v1
clusters:
  - name: duploinfra-reddit
    cluster:
      server: https://47c51c64a8d165d8aeda8c466a6ff4db.gr7.us-west-2.eks.amazonaws.com
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXpNREUzTWpVeU9Gb1hEVE16TURVeU56RTNNalV5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGV0CmU5VzR2TE1kY3h6ZStHVGdMeS80STdEVW91ZDljSFR4UjVYSTVwTVNMZHNkK2lvTzFwVnU0eStyUEVmQ1NqcG4KYmhxUVFqYWdLM3FwWWxoY1RMRWVZNS9qNDdXRHVkR1RPVVBhME9VcTVUdmJXcnZ0ZCtqbm9ZNVNrUWZKalVuNgoxM3FtWlJjWG1aRzBLYS8xRlhrblprcWJmWllUSGFiUDMvS2krdEQ3M0IxL0twc29aOHFxUkZBMzBKVk5CS20xCmdyOUhITW8wYlRvVS95WFZpQ2ZQSHNoNE1ncHlJM0FvVitGL2puODNvN2NlOThya3Q4cFY1a2RsNm9Pb3FZeGUKNXMyMk5SM1hENFM0MnVZU3VSbFg3U3hNcnE3dU5YU2JVL1ZSbHJTbTZESXdFNXU3YURyNzN3SWlkK0EyZGNZTQo4V01DRWozOHlueUxNRXA2NnA4Q0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLcmtJTUFCc21XTC8wMERlbFJWQzFkRXd2RnNNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0JZeXpROXlIbmZZeGJIVTRUUwozNnJrNFJ6eXYxRC90NTdVTHdQSUV3bFdSc09xTHRTODlIajNUaklFUytuOG40UDhHNjNTRmJ6SUR5R3lBajdECkVxNXNQWTd2MERsbWdhYkdWaGdBRjFlMlQ4V3JOZi9IcnVqaXF5SXAyRHQxN1JWR3dFaWU5a0t0ZGhhbXpJdVgKNTlPUU1Wam1PVGFWclRHaVdoUDQvbVhzd2tWNURmZUxGaWo1Q3lOLzV4dzl6dktjYWwrWU55NTBOY0I2aGd4bwp1RnpQMGh1dGRDM24wb3BBckdTcDA2RjU4UWpGRmhlZUo3K0FDdU1mb3B1ZVVJWk9Fc2x3TVE5amRVQlRpZkErCnhYRUszYUFDVjRlaEtzZUQ1RkN1VlV5SVpCV2dsaDBMMWUwY0Ztdk1lb2o2ZmdNOEF2TndpSHh6RUlTUVBxbVQKQXFBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
contexts:
  - name: duploinfra-reddit
    context:
      namespace: kube-system
      user: duploinfra-reddit
      cluster: duploinfra-reddit
users:
  - name: duploinfra-reddit
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: duplo-jit
        installHint: |-
          Install duplo-jit for use with kubectl by following
           https://github.com/duplocloud/duplo-jit
        args:
          - k8s
          - '--plan'
          - reddit
          - '--host'
          - https://galileo.duplocloud.net/
          - '--token'
          - '<DUPLO_TOKEN>'
current-context: duploinfra-reddit
