apiVersion: v1
clusters:
  - name: <CLUSTER_NAME>
    cluster:
      server: <KUBERNETES_ENDPOINT>
      certificate-authority-data: >-
        <KUBERNETES_CERT_DATA>
contexts:
  - name: <CLUSTER_NAME>
    context:
      namespace: kube-system
      user: <CLUSTER_NAME>
      cluster: <CLUSTER_NAME>
users:
  - name: <CLUSTER_NAME>
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: duplo-jit
        installHint: |-
          Install duplo-jit for use with kubectl by following
           https://github.com/duplocloud/duplo-jit
        args:
          - k8s
          - '--plan'
          - <DUPLO_INFRA_NAME>
          - '--host'
          - https://galileo.duplocloud.net/
          - '--token'
          - '<DUPLO_TOKEN>'
current-context: <CLUSTER_NAME>
