name: Deploy ECS Demo
on:
  push:
    branches:
      - master
  workflow_dispatch:  # magically allow triggering from the UI
env:
  GIT_COMMIT: ${{ github.sha }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DUPLO_HOST: https://msp.duplocloud.net
  DUPLO_TOKEN: ${{ secrets.MSP_DEMO_DUPLO_TOKEN }}
  DUPLO_TENANT_ID: "151a7738-d885-4ba6-a52d-8ebc6ba1fd66"
jobs:
  image-demoservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker login
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Docker Build
        run: docker build -t "duplocloud/anyservice:demoservice-${GIT_COMMIT}" .
      - name: Docker Push
        run: docker push "duplocloud/anyservice:demoservice-${GIT_COMMIT}"
  deploy-demoservice:
    runs-on: ubuntu-latest
    needs:
      - image-demoservice
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: pip install requests logger
      - name: Deploy
        run: python ecs-deploy-job.py "cicddemo" "duplocloud/anyservice:demoservice-${GIT_COMMIT}"
