name: Deploy kubernetes
on:
  push:
    branches:
      - master
  workflow_dispatch:  # magically allow triggering from the UI
env:
  DUPLO_HOST: https://galileo.duplocloud.net
  DUPLO_TOKEN: ${{ secrets.DUPLO_API_TOKEN }}
jobs:
  deploy-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup duplo-jit
        run: |
          curl https://github.com/duplocloud/duplo-jit/releases/download/v0.5.4/duplo-jit_0.5.4_linux_386.zip -L -o duplo-jit.zip
          unzip duplo-jit.zip -d duplo_jit_unzipped
          cp duplo_jit_unzipped/duplo-jit /usr/local/bin/

      - name: Run kubectl
        run: |
          export KUBECONFIG=kubeconfig.yaml
          sed -i 's#<DUPLO_TOKEN>#${{ secrets.GALILEO_API_TOKEN }}#' kubeconfig.yaml
          kubectl get ns
          